# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kelsey Hammer
email: khammer19@gmail.com
description: Shatters Glass. Forges Steel. Pronounces Gif Correctly. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: kel_hammer
github_username:  kelhammer

# Build settings
markdown: kramdown
